---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    fabric8.io/git-commit: 13082281d0090facee35514234a43e5d7d85670d
    fabric8.io/iconUrl: img/icons/spring-boot.svg
    fabric8.io/git-branch: master
    fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=apiserver&var-version=LocalBuild
    fabric8.io/scm-tag: HEAD
    fabric8.io/scm-url: https://github.com/spring-projects/spring-boot/spring-boot-starter-parent/parent/apiserver
  labels:
    app: apiserver
    provider: fabric8
    version: LocalBuild
    group: de.bdr.labdays
  name: apiserver
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: apiserver
      provider: fabric8
      group: de.bdr.labdays
  template:
    metadata:
      annotations:
        fabric8.io/git-commit: 13082281d0090facee35514234a43e5d7d85670d
        fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=apiserver&var-version=LocalBuild
        fabric8.io/scm-url: https://github.com/spring-projects/spring-boot/spring-boot-starter-parent/parent/apiserver
        fabric8.io/iconUrl: img/icons/spring-boot.svg
        fabric8.io/git-branch: master
        fabric8.io/scm-tag: HEAD
      labels:
        app: apiserver
        provider: fabric8
        version: LocalBuild
        group: de.bdr.labdays
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: apiserver:LocalBuild
        imagePullPolicy: IfNotPresent
        name: spring-boot
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 9779
          name: prometheus
          protocol: TCP
        - containerPort: 8778
          name: jolokia
          protocol: TCP
        securityContext:
          privileged: false
