---
apiVersion: v1
kind: Service
metadata:
  annotations:
    fabric8.io/git-commit: 13082281d0090facee35514234a43e5d7d85670d
    prometheus.io/port: "9779"
    fabric8.io/scm-url: https://github.com/spring-projects/spring-boot/spring-boot-starter-parent/parent/webapp
    fabric8.io/iconUrl: img/icons/spring-boot.svg
    fabric8.io/git-branch: master
    prometheus.io/scrape: "true"
    fabric8.io/scm-tag: HEAD
  labels:
    app: webapp
    provider: fabric8
    version: LocalBuild
    group: de.bdr.labdays
  name: webapp
spec:
  ports:
  - name: sunproxyadmin
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: webapp
    provider: fabric8
    group: de.bdr.labdays
